name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up JDK
        uses: actions/setup-java@v5.0.0
        with:
          java-version: 11
          distribution: 'adopt'
          check-latest: true

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v4.2.4
        with:
          path: ~/.m2/repository
          key: pit-stryker-dashboard-reporter-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            pit-stryker-dashboard-reporter

      - name: Build and test code
        run: mvn -B verify --no-transfer-progress
