name: Mutation testing

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  mutationtesting:
    if: contains(github.event.head_commit.message, 'maven-release-plugin') != true
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 11
          distribution: 'adopt'
          cache: maven

      - name: Install reporter
        run: mvn -B --no-transfer-progress install

      - name: Run Pitest and upload report
        run: mvn -B -e --no-transfer-progress test-compile org.pitest:pitest-maven:mutationCoverage -Dverbose
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
