name: SonarCloud analysis

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2/repository
          key: pit-stryker-dashboard-reporter-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'adopt'
          check-latest: true

      - name: SonarCloud Scan
        run: |
          mvn -B -Dsonar.login=$SONAR_TOKEN --no-transfer-progress verify sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
